# Generated by Django 4.1.7 on 2023-04-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=150)),
                ('news_post', models.TextField()),
                ('news_author', models.CharField(max_length=70)),
                ('news_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Supply_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_title', models.CharField(max_length=150)),
                ('supply_post', models.TextField()),
                ('supply_author', models.CharField(max_length=70)),
            ],
        ),
    ]
